### ISSUE TITLE
Can't seem to get the the classes parameter to work

### ISSUE THREAD

**Issue by pixelsock** [eliot-akira/custom-content-shortcode#3]
[related location_select]
[pass field=menu_title]
[loop menu="{FIELD}" list=true li_class=custom_li_class]
[field title-link]
[/loop]
[/pass]
[/related]

This doesn't seem to be working. I've tried adding it to every shortcode in this setup. I've tried just class= and removing list=true. Can you help or explain how to add classes to fields? The [field title-link] needs to be able to have a class, but I just can't figure it out.

**Comment by eliot-akira** [comment]
This should work:

```
[link class="field-class"][field title][/link]
```
