### ISSUE TITLE
Error: Undefined variable: thousands

### ISSUE THREAD

**Issue by codemonkeynorth** [eliot-akira/custom-content-shortcode#9]
Hi,

you're trying to check `$thousands` variable before it is assigned.

`$thousands = !empty($atts['thousands']) ? ($thousands==='false' ? '' : $atts['thousands']) : '';`

in `includes\modules\format.php`

this throws an error:
`Undefined variable: thousands`

(currently this means I have to turn debug off on my dev site to prevent from happening)

maybe you mean to check  `$atts['thousands']==='false'` ?

thanks
J

**Comment by eliot-akira** [comment]
Fixed by pull request #14.
